import { useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, BookCopy, Check, ChevronDown, Copy, Download, Eraser, FileText, Highlighter, ImagePlus, LoaderCircle, PenTool, Plus, Presentation, Redo2, RotateCcw, Save, Search, Sparkles, Trash2, Undo2, X } from "lucide-react";
import type { ConsultationAsset, ConsultationAssetFormat, ConsultationDocumentDraft, ConsultationDocumentOptions, ConsultationMemo, NormalizedResearchMaterial, ProjectNextAction, ResearchOutline, ResearchProject, ResearchProjectCover, ResearchProjectVersion } from "../../shared/research-project";
import { api } from "../lib/api";
import { loadQuestionMaterials, materialTypeLabel } from "../lib/questionMaterials";
import { Button, Card, Chip, ErrorState, Skeleton } from "../components/ui";
import { ProjectCover } from "../components/ProjectCover";

type Tab = "outline"|"questions"|"assets"|"memos"|"materials"|"versions"|"cover";
const TABS: [Tab,string][] = [["outline","現在の骨子"],["questions","問い案"],["assets","相談資料"],["memos","相談メモ"],["materials","関連素材"],["versions","バージョン"],["cover","表紙"]];
const EMPTY_MEMO = { versionId:"", consultationDate:new Date().toISOString().slice(0,10), person:"", affiliation:"", comments:"", critiques:"", references:"", rqRevision:"", targetRevision:"", methodRevision:"", nextActions:"", reflection:"", referenceUrl:"" };

export default function ProjectDetail() {
  const { id = "" } = useParams();
  const [project,setProject] = useState<ResearchProject|null>(null);
  const [memos,setMemos] = useState<ConsultationMemo[]>([]);
  const [materials,setMaterials] = useState<NormalizedResearchMaterial[]>([]);
  const [tab,setTab] = useState<Tab>(()=>new URLSearchParams(window.location.search).get("tab")==="cover"?"cover":"outline");
  const [state,setState] = useState<"loading"|"error"|"ok">("loading");
  const load = () => { setState("loading"); Promise.all([api.getProject(id),api.getProjectMemos(id),loadQuestionMaterials()]).then(([p,m,all]) => { setProject(p.project); setMemos(m.memos); setMaterials(all); setState("ok"); }).catch(() => setState("error")); };
  useEffect(load,[id]);
  if (state === "loading") return <div className="max-w-6xl mx-auto px-4 py-8"><Skeleton className="h-72"/><Skeleton className="h-96 mt-4"/></div>;
  if (state === "error" || !project) return <div className="max-w-4xl mx-auto px-4 py-8"><ErrorState onRetry={load}/></div>;
  return <div className="project-detail-page max-w-6xl mx-auto px-4 md:px-6 py-5 md:py-8">
    <Helmet><title>{project.displayTitle} ｜ 本棚</title></Helmet>
    <Link to="/projects" className="back-link"><ArrowLeft/>本棚へ戻る</Link>
    <header className="project-detail-header"><ProjectCover project={project} compact/><div><div className="project-title-row"><span className={`status-dot ${project.status}`}>{project.status === "draft" ? "作成中" : project.status === "consultation" ? "相談用" : "保留"}</span><span>v{project.versions.find((v) => v.versionId === project.currentVersionId)?.versionNumber || 1}</span></div><h1>{project.displayTitle}</h1><p>{project.subtitle}</p><small>更新 {new Date(project.updatedAt).toLocaleString("ja-JP")}</small></div><label className="header-status">状態<select value={project.status} onChange={async(e) => { const {project:next}=await api.updateProject(id,{status:e.target.value as ResearchProject['status']}); setProject(next); }}><option value="draft">作成中</option><option value="consultation">相談用</option><option value="on_hold">保留</option></select></label></header>
    <nav className="project-tabs">{TABS.map(([key,label]) => <button key={key} className={tab===key?"active":""} onClick={() => setTab(key)}>{label}{key==="memos" && memos.length>0 && <b>{memos.length}</b>}</button>)}</nav>
    {tab === "outline" && <OutlineEditor project={project} onProject={setProject}/>} 
    {tab === "questions" && <QuestionCandidates project={project}/>} 
    {tab === "assets" && <ConsultationAssets project={project} onProject={setProject}/>}
    {tab === "memos" && <MemoPanel project={project} memos={memos} onMemos={setMemos}/>} 
    {tab === "materials" && <MaterialsPanel project={project} materials={materials} onProject={setProject}/>} 
    {tab === "versions" && <VersionsPanel project={project} onProject={setProject}/>} 
    {tab === "cover" && <CoverEditor project={project} onProject={setProject}/>} 
  </div>;
}

function OutlineEditor({project,onProject}:{project:ResearchProject;onProject:(p:ResearchProject)=>void}) {
  const [outline,setOutline] = useState(project.step2Response.research_outline);
  const [saveState,setSaveState] = useState<"saved"|"saving"|"error">("saved");
  const [dirty,setDirty] = useState(false);
  const initial = useRef(true);
  useEffect(() => { setOutline(project.step2Response.research_outline); initial.current=true; setDirty(false); },[project.currentVersionId]);
  useEffect(() => {
    if (initial.current) { initial.current=false; return; }
    setDirty(true); setSaveState("saving");
    const timer=setTimeout(async()=>{ try { const response={...project.step2Response,research_outline:outline}; const {project:next}=await api.updateProject(project.id,{step2Response:response}); onProject(next); setDirty(false); setSaveState("saved"); } catch { setSaveState("error"); } },750);
    return()=>clearTimeout(timer);
  },[outline]);
  useEffect(()=>{ const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}}; window.addEventListener("beforeunload",warn); return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  const set=(key:keyof ResearchOutline,value:any)=>setOutline((o)=>({...o,[key]:value}));
  const makeVersion=async()=>{ const name=prompt("新しいバージョン名","対象を絞った案"); if(!name)return; const reason=prompt("変更理由","現在の骨子から複製")||"現在の骨子から複製"; await api.createProjectVersion(project.id,{versionName:name,changeReason:reason,creationType:"manual_duplicate",step2Response:{...project.step2Response,research_outline:outline},carryMemos:true}); const {project:next}=await api.getProject(project.id); onProject(next); };
  const regenerate=async()=>{ const reason=prompt("AIで全体を再生成する方向・理由を入力してください","対象を絞り、実施可能性を高める")||"AI全体再生成"; const {project:next}=await api.regenerateProject(project.id,{versionName:`v${project.versions.length+1} AI再生成`,changeReason:reason,carryMemos:true}); onProject(next); };
  return <section className="project-panel outline-editor"><div className="editor-toolbar"><div><h2>現在の骨子</h2><span className={`save-state ${saveState}`}>{saveState==="saving"?<><LoaderCircle/>保存中</>:saveState==="saved"?<><Check/>保存済み</>:"保存に失敗"}</span></div><div><Button variant="secondary" onClick={makeVersion}><BookCopy/>新しい版として複製</Button><Button onClick={regenerate}><Sparkles/>全体をAIで再生成</Button></div></div>
    <p className="editor-note">AIの調整は項目単位です。文章を選択した場合は選択部分だけを置き換え、手動編集した他の項目は保持します。</p>
    <div className="outline-form"><Field label="一般向けタイトル" value={outline.title_public} onChange={(v)=>set("title_public",v)} project={project}/><Field label="学術向けタイトル" value={outline.title_academic} onChange={(v)=>set("title_academic",v)} project={project}/><Field label="研究の中心的な意味・仕組み（内部キー: mim）" value={outline.mim} onChange={(v)=>set("mim",v)} project={project}/>
      <Field label="背景" value={outline.background} onChange={(v)=>set("background",v)} project={project}/><Field label="問題" value={outline.problem} onChange={(v)=>set("problem",v)} project={project}/><Field label="目的" value={outline.purpose} onChange={(v)=>set("purpose",v)} project={project}/><Field label="メインRQ" value={outline.main_rq} onChange={(v)=>set("main_rq",v)} project={project}/><ArrayField label="サブRQ" value={outline.sub_rqs} onChange={(v)=>set("sub_rqs",v)} project={project}/><Field label="先行研究との差分" value={outline.related_work_diff} onChange={(v)=>set("related_work_diff",v)} project={project}/><ArrayField label="概念モデル" value={outline.conceptual_model} onChange={(v)=>set("conceptual_model",v)} project={project}/><Field label="研究デザイン" value={outline.research_design} onChange={(v)=>set("research_design",v)} project={project}/><Field label="対象" value={outline.target_population} onChange={(v)=>set("target_population",v)} project={project}/><Field label="データ収集" value={outline.data_collection} onChange={(v)=>set("data_collection",v)} project={project}/><Field label="分析方法" value={outline.analysis_method} onChange={(v)=>set("analysis_method",v)} project={project}/><Field label="評価方法" value={outline.evaluation_method} onChange={(v)=>set("evaluation_method",v)} project={project}/><Field label="倫理的配慮" value={outline.ethical_considerations} onChange={(v)=>set("ethical_considerations",v)} project={project}/>
      <Field label="学術的意義" value={outline.significance.academic} onChange={(v)=>set("significance",{...outline.significance,academic:v})} project={project}/><Field label="実務的意義" value={outline.significance.practical} onChange={(v)=>set("significance",{...outline.significance,practical:v})} project={project}/><Field label="社会的意義" value={outline.significance.social} onChange={(v)=>set("significance",{...outline.significance,social:v})} project={project}/><Field label="限界" value={outline.limitations} onChange={(v)=>set("limitations",v)} project={project}/><ArrayField label="次のステップ" value={outline.next_steps} onChange={(v)=>set("next_steps",v)} project={project}/>
      <div className="outline-divider"><span>相談に持っていくための項目</span></div><Field label="研究として面白そうな点" value={outline.interesting_points} onChange={(v)=>set("interesting_points",v)} project={project}/><ArrayField label="難しそうな点" value={outline.difficult_points} onChange={(v)=>set("difficult_points",v)} project={project}/><ArrayField label="相談したいこと" value={outline.consultation_questions} onChange={(v)=>set("consultation_questions",v)} project={project}/><ArrayField label="コメント" value={outline.comments} onChange={(v)=>set("comments",v)} project={project}/><NextActions value={outline.next_actions} onChange={(v)=>set("next_actions",v)}/>
    </div></section>;
}

function Field({label,value,onChange,project}:{label:string;value:string;onChange:(v:string)=>void;project:ResearchProject}) {
  const ref=useRef<HTMLTextAreaElement>(null); const [busy,setBusy]=useState(false);
  const adjust=async(instruction:string)=>{const start=ref.current?.selectionStart||0,end=ref.current?.selectionEnd||0,selected=value.slice(start,end);setBusy(true);try{const result=await api.adjustResearchText(selected||value,instruction,project.selectedRq.public_rq);onChange(selected?`${value.slice(0,start)}${result.value}${value.slice(end)}`:result.value);}finally{setBusy(false);}};
  return <label className="outline-field"><span>{label}</span><textarea ref={ref} rows={Math.max(2,Math.min(7,value.split("\n").length+1))} value={value} onChange={(e)=>onChange(e.target.value)}/><details className="ai-field-menu"><summary>{busy?<LoaderCircle className="animate-spin"/>:<Sparkles/>}AIで調整<ChevronDown/></summary><div>{["言い換える","短くする","詳しくする","学術的な表現にする","初学者向けにする","対象を絞る","方法を変える"].map((action)=><button type="button" key={action} onClick={()=>adjust(action)}>{action}</button>)}</div></details></label>;
}
function ArrayField({label,value,onChange,project}:{label:string;value:string[];onChange:(v:string[])=>void;project:ResearchProject}) { return <Field label={`${label}（1行に1項目）`} value={value.join("\n")} onChange={(v)=>onChange(v.split("\n").map((x)=>x.trim()).filter(Boolean))} project={project}/>; }
function NextActions({value,onChange}:{value:ProjectNextAction[];onChange:(v:ProjectNextAction[])=>void}) { const add=()=>onChange([...value,{id:`action-${Date.now()}`,text:"",completed:false}]); return <fieldset className="next-actions"><legend>次にやること</legend>{value.map((item,index)=><div key={item.id}><input type="checkbox" checked={item.completed} onChange={(e)=>onChange(value.map((x,i)=>i===index?{...x,completed:e.target.checked}:x))}/><input value={item.text} placeholder="やること" onChange={(e)=>onChange(value.map((x,i)=>i===index?{...x,text:e.target.value}:x))}/><input type="date" value={item.dueDate||""} onChange={(e)=>onChange(value.map((x,i)=>i===index?{...x,dueDate:e.target.value}:x))}/><button type="button" onClick={()=>onChange(value.filter((_,i)=>i!==index))}><X/></button></div>)}<button type="button" onClick={add}><Plus/>項目を追加</button></fieldset>; }

function QuestionCandidates({project}:{project:ResearchProject}) { return <section className="project-panel"><div className="panel-heading"><div><p className="eyebrow">STEP 1 ARCHIVE</p><h2>問い案</h2></div><Chip tone="yellow">採用中：{project.selectedRq.type_name}</Chip></div><div className="rq-grid">{project.rqCandidates.map((rq)=><Card key={`${rq.type_name}-${rq.rq_title}`} className={rq.academic_rq===project.selectedRq.academic_rq?"rq-card chosen":"rq-card"}><Chip tone={rq.is_recommended?"yellow":"blue"}>{rq.type_name}</Chip><h3>{rq.rq_title}</h3><p className="rq-public">{rq.public_rq}</p><details><summary>設計を見る<ChevronDown/></summary><dl><Info label="専門向けRQ" value={rq.academic_rq}/><Info label="方法" value={rq.methods}/><Info label="想定成果物" value={rq.expected_output}/><Info label="難易度" value={rq.difficulty}/></dl></details></Card>)}</div></section>; }
function ConsultationAssets({project,onProject}:{project:ResearchProject;onProject:(project:ResearchProject)=>void}) {
  const [format,setFormat]=useState<ConsultationAssetFormat>("pdf");
  const [assets,setAssets]=useState<ConsultationAsset[]>([]);
  const [draft,setDraft]=useState<ConsultationDocumentDraft|null>(null);
  const [options,setOptions]=useState<ConsultationDocumentOptions>({includeCover:true,includeComments:true,includeNextActions:true,includeMaterials:false,showEmpty:false});
  const [busy,setBusy]=useState<"loading"|"generating"|"adjusting"|"">("loading"); const [error,setError]=useState("");
  const load=async()=>{setBusy("loading");try{const [{assets:items},{draft:next}]=await Promise.all([api.getConsultationAssets(project.id),api.previewConsultationAsset(project.id,format,options)]);setAssets(items);setDraft(next);setError("");}catch(e){setError(e instanceof Error?e.message:"相談資料を読み込めませんでした");}finally{setBusy("");}};
  useEffect(()=>{load();},[project.id,format]);
  const refreshPreview=async()=>{setBusy("loading");try{const {draft:next}=await api.previewConsultationAsset(project.id,format,options);setDraft(next);setError("");}catch(e){setError(e instanceof Error?e.message:"プレビューを作れませんでした");}finally{setBusy("");}};
  const changeSection=(label:string,value:string)=>setDraft((current)=>current?{...current,sections:{...current.sections,[label]:value.split("\n").filter(Boolean)}}:current);
  const adjust=async(label:string,instruction:string)=>{if(!draft)return;setBusy("adjusting");try{const value=draft.sections[label].join("\n");const result=await api.adjustResearchText(value,instruction,project.selectedRq.public_rq);changeSection(label,result.value);if(!result.aiEnabled)setError("Gemini未設定のため文章は変更されませんでした。手動編集と決定論的な抜粋で生成できます。");}finally{setBusy("");}};
  const generate=async()=>{if(!draft)return;setBusy("generating");setError("");try{const result=await api.generateConsultationAsset(project.id,format,draft);setAssets((items)=>[result.asset,...items]);onProject(result.project);}catch(e){setError(e instanceof Error?e.message:"生成に失敗しました");}finally{setBusy("");}};
  const remove=async(asset:ConsultationAsset)=>{if(!confirm("この生成済み資料を削除しますか？"))return;await api.deleteConsultationAsset(project.id,asset.id);setAssets((items)=>items.filter((item)=>item.id!==asset.id));};
  const currentAssets=assets.filter((asset)=>asset.format===format); const tooLong=draft?Object.values(draft.sections).some((values)=>values.join("").length>(format==="pdf"?1800:format==="pptx_1"?520:800)):false;
  return <section className="project-panel consultation-assets"><div className="panel-heading"><div><p className="eyebrow">CONSULTATION ASSETS</p><h2>相談資料</h2></div><span>固定テンプレートで生成</span></div>
    <div className="asset-format-tabs">{([['pdf','PDF',FileText],['pptx_1','1枚スライド',Presentation],['pptx_2','2枚スライド',Presentation],['pptx_3','3枚スライド',Presentation]] as const).map(([id,label,Icon])=><button key={id} className={format===id?'active':''} onClick={()=>setFormat(id)}><Icon/>{label}</button>)}</div>
    {format==="pdf"&&<Card className="asset-options"><strong>PDF生成オプション</strong>{([['includeCover','表紙'],['includeComments','コメント'],['includeNextActions','次にやること'],['includeMaterials','関連素材'],['showEmpty','空項目']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={(e)=>setOptions({...options,[key]:e.target.checked})}/>{label}</label>)}<Button variant="secondary" onClick={refreshPreview}><RotateCcw/>反映</Button></Card>}
    {error&&<p className="form-error" role="alert">{error}</p>}{tooLong&&<p className="asset-warning"><AlertTriangle/>文章量が多めです。極端に文字を小さくせずに収めるため、生成前に一部を短くしてください。</p>}
    {busy==="loading"||!draft?<div className="grid gap-3"><Skeleton className="h-28"/><Skeleton className="h-28"/></div>:<div className="asset-editor"><div className="asset-preview-head"><div><strong>{draft.title}</strong><p>{draft.subtitle}</p></div><Button onClick={generate} disabled={busy==="generating"}>{busy==="generating"?<LoaderCircle className="animate-spin"/>:<Save/>}{currentAssets.length?'再生成':'生成する'}</Button></div><div className="asset-section-grid">{Object.entries(draft.sections).map(([label,values])=><Card key={label} className="asset-section"><label><span>{label}</span><textarea rows={Math.max(3,Math.min(8,values.length+2))} value={values.join("\n")} onChange={(e)=>changeSection(label,e.target.value)}/></label><div>{['短くする','分かりやすくする','研究者向けにする','相談相手向けにする'].map((action)=><button key={action} disabled={!!busy} onClick={()=>adjust(label,action)}><Sparkles/>{action}</button>)}</div></Card>)}</div></div>}
    <div className="generated-assets"><h3>生成履歴</h3>{currentAssets.length===0?<p>この形式の資料はまだ生成されていません。</p>:currentAssets.map((asset)=><Card key={asset.id} className="generated-asset"><div><Chip tone={asset.status==='ready'?'teal':asset.status==='outdated'?'yellow':'default'}>{asset.status==='ready'?'利用可能':asset.status==='outdated'?'更新前の資料':asset.status==='error'?'生成エラー':'生成中'}</Chip><strong>{asset.format==='pdf'?'研究骨子・相談セットPDF':`${asset.pageCount}枚スライド`}</strong><small>{new Date(asset.generatedAt).toLocaleString('ja-JP')} ・ {asset.pageCount}ページ</small>{asset.error&&<p>{asset.error}</p>}</div><div>{asset.filePath&&<a className="asset-download" href={api.consultationAssetDownloadUrl(project.id,asset.id)}><Download/>ダウンロード</a>}<button onClick={()=>remove(asset)} aria-label="資料を削除"><Trash2/></button></div></Card>)}</div>
  </section>;
}

function MemoPanel({project,memos,onMemos}:{project:ResearchProject;memos:ConsultationMemo[];onMemos:(m:ConsultationMemo[])=>void}) {
  const [form,setForm]=useState(EMPTY_MEMO); const [editing,setEditing]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const save=async()=>{setBusy(true);try{if(editing){const {memo}=await api.updateProjectMemo(project.id,editing,form);onMemos(memos.map((m)=>m.id===editing?memo:m));}else{const {memo}=await api.createProjectMemo(project.id,form);onMemos([memo,...memos]);}setForm(EMPTY_MEMO);setEditing(null);}finally{setBusy(false);}};
  const edit=(memo:ConsultationMemo)=>{setEditing(memo.id);setForm({...EMPTY_MEMO,...memo});window.scrollTo({top:0,behavior:"smooth"});};
  return <section className="project-panel memo-panel"><div className="panel-heading"><div><p className="eyebrow">CONSULTATION LOG</p><h2>相談メモ</h2></div><span>{memos.length}件</span></div><Card className="memo-form"><h3>{editing?"相談メモを編集":"相談の記録を追加"}</h3><div className="memo-grid"><label>相談日<input type="date" value={form.consultationDate} onChange={(e)=>setForm({...form,consultationDate:e.target.value})}/></label><label>紐づけるVersion<select value={form.versionId} onChange={(e)=>setForm({...form,versionId:e.target.value})}><option value="">Project全体</option>{project.versions.map((v)=><option value={v.versionId} key={v.versionId}>{v.versionName}</option>)}</select></label><label>相談相手<input value={form.person} onChange={(e)=>setForm({...form,person:e.target.value})}/></label><label>相手の所属・関係<input value={form.affiliation} onChange={(e)=>setForm({...form,affiliation:e.target.value})}/></label>{memoFields.map(([key,label])=><label key={key} className="wide">{label}<textarea rows={3} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="dialog-actions">{editing&&<Button variant="ghost" onClick={()=>{setEditing(null);setForm(EMPTY_MEMO);}}>編集をやめる</Button>}<Button onClick={save} disabled={busy||!form.consultationDate}>{busy&&<LoaderCircle className="animate-spin"/>}<Save/>保存</Button></div></Card><div className="memo-list">{memos.map((memo)=><Card key={memo.id} className="memo-card"><div><span>{new Date(memo.consultationDate).toLocaleDateString("ja-JP")}</span>{memo.versionId?<Chip tone="blue">{project.versions.find((v)=>v.versionId===memo.versionId)?.versionName||"Version"}</Chip>:<Chip>Project全体</Chip>}<button onClick={()=>edit(memo)}>編集</button></div><h3>{memo.person||"相談相手未記入"}<small>{memo.affiliation}</small></h3>{memo.comments&&<Info label="もらったコメント" value={memo.comments}/>} {memo.critiques&&<Info label="指摘" value={memo.critiques}/>} {memo.nextActions&&<Info label="次にやること" value={memo.nextActions}/>} {memo.referenceUrl&&<a href={memo.referenceUrl} target="_blank" rel="noreferrer">参照URLを開く</a>}</Card>)}</div></section>;
}
const memoFields = [["comments","もらったコメント"],["critiques","指摘"],["references","読むべき文献"],["rqRevision","RQの修正"],["targetRevision","対象の修正"],["methodRevision","方法の修正"],["nextActions","次にやること"],["reflection","自分の感想"],["referenceUrl","参照URL"]] as [keyof typeof EMPTY_MEMO,string][];

function MaterialsPanel({project,materials,onProject}:{project:ResearchProject;materials:NormalizedResearchMaterial[];onProject:(p:ResearchProject)=>void}) {
  const [adding,setAdding]=useState(false); const [query,setQuery]=useState(""); const [typeFilter,setTypeFilter]=useState("all"); const related=new Set(project.sourceMaterials.map(materialKey));
  const types=useMemo(()=>Array.from(new Set([...project.sourceMaterials,...materials].map((item)=>item.sourceType))).sort(),[project.sourceMaterials,materials]);
  const matches=(item:NormalizedResearchMaterial)=>{const q=query.trim().toLowerCase();const text=[item.title,item.officialDescription,item.excerpt,item.userReaction,item.userReasonMemo,...(item.sourceKeywords||[]),...(item.approvedTags||[])].filter(Boolean).join(" ").toLowerCase();return(typeFilter==="all"||item.sourceType===typeFilter)&&(!q||text.includes(q));};
  const visibleRelated=project.sourceMaterials.filter(matches); const available=materials.filter((item)=>!related.has(materialKey(item))&&matches(item));
  const save=async(next:NormalizedResearchMaterial[])=>{const {project:p}=await api.updateProject(project.id,{sourceMaterials:next,relatedMaterialIds:next.map((x)=>x.sourceId)});onProject(p);};
  return <section className="project-panel"><div className="panel-heading"><div><p className="eyebrow">SOURCE SNAPSHOT</p><h2>関連素材</h2></div><Button variant="secondary" onClick={()=>setAdding(!adding)}><Plus/>素材を追加</Button></div><div className="material-filter-bar"><label><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="タイトル・説明・タグ・メモを検索"/></label><select aria-label="素材の種類" value={typeFilter} onChange={(e)=>setTypeFilter(e.target.value)}><option value="all">すべての種類</option>{types.map((type)=><option value={type} key={type}>{materialTypeLabel[type]||type}</option>)}</select><span>{visibleRelated.length} / {project.sourceMaterials.length}件</span></div>{adding&&<Card className="material-picker"><h3>「ためる」から追加</h3><div className="material-grid">{available.map((item)=><button key={materialKey(item)} className="material-option" onClick={()=>save([...project.sourceMaterials,item])}><Plus/><span><Chip tone="blue">{materialTypeLabel[item.sourceType]}</Chip><strong>{item.title}</strong><em>{item.excerpt||item.officialDescription}</em></span></button>)}</div>{available.length===0&&<p className="material-filter-empty">条件に合う追加候補はありません</p>}</Card>}<div className="related-material-list">{visibleRelated.map((item)=><Card key={materialKey(item)}><div><Chip tone="blue">{materialTypeLabel[item.sourceType]||item.sourceType}</Chip><strong>{item.title}</strong>{item.excerpt&&<p>{item.excerpt}</p>}<small>{[item.userReaction,item.userReasonMemo].filter(Boolean).join(" ・ ")}</small></div><button onClick={()=>save(project.sourceMaterials.filter((x)=>materialKey(x)!==materialKey(item)))} title="関連から外す"><Trash2/></button></Card>)}</div>{project.sourceMaterials.length===0&&<Card className="phase-empty"><p>関連素材はまだありません。「素材を追加」から、ためた研究室・領域・マーキングなどを紐づけられます。</p></Card>}{project.sourceMaterials.length>0&&visibleRelated.length===0&&<Card className="phase-empty"><p>検索条件に合う関連素材はありません</p></Card>}</section>;
}

function VersionsPanel({project,onProject}:{project:ResearchProject;onProject:(p:ResearchProject)=>void}) {
  const [compare,setCompare]=useState<string[]>([]); const [form,setForm]=useState({name:"",reason:"",carryMemos:true});
  const create=async()=>{if(!form.name.trim())return;await api.createProjectVersion(project.id,{versionName:form.name,changeReason:form.reason,creationType:"manual_duplicate",carryMemos:form.carryMemos});const {project:p}=await api.getProject(project.id);onProject(p);setForm({name:"",reason:"",carryMemos:true});};
  const select=async(versionId:string)=>{const {project:p}=await api.selectProjectVersion(project.id,versionId);onProject(p);};
  const compared=project.versions.filter((v)=>compare.includes(v.versionId));
  return <section className="project-panel versions-panel"><div className="panel-heading"><div><p className="eyebrow">VERSION HISTORY</p><h2>バージョン</h2></div><span>一冊の中に {project.versions.length}案</span></div><Card className="version-create"><h3>現在案から新Versionを作る</h3><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder={`v${project.versions.length+1} 対象を絞った案`}/><input value={form.reason} onChange={(e)=>setForm({...form,reason:e.target.value})} placeholder="変更理由"/><label><input type="checkbox" checked={form.carryMemos} onChange={(e)=>setForm({...form,carryMemos:e.target.checked})}/>相談メモを引き継ぐ</label><Button onClick={create}><BookCopy/>作成</Button></Card><div className="version-list">{[...project.versions].reverse().map((v)=><Card key={v.versionId} className={project.currentVersionId===v.versionId?"current":""}><div><span>v{v.versionNumber}</span><div><h3>{v.versionName}</h3><p>{v.changeReason}</p><small>{new Date(v.createdAt).toLocaleString("ja-JP")} ・ {creationLabel[v.creationType]}</small></div></div><div><label><input type="checkbox" checked={compare.includes(v.versionId)} onChange={()=>setCompare(toggle(compare,v.versionId).slice(-2))}/>比較</label>{project.currentVersionId===v.versionId?<Chip tone="yellow">現在版</Chip>:<Button variant="secondary" onClick={()=>select(v.versionId)}>この版を開く</Button>}</div></Card>)}</div>{compared.length===2&&<VersionCompare versions={compared}/>}</section>;
}
const creationLabel:Record<string,string>={initial:"初回案",manual_duplicate:"手動複製",ai_regeneration:"AI再生成",consultation_revision:"相談後の改訂"};
function VersionCompare({versions}:{versions:ResearchProjectVersion[]}) { const fields:[string,(v:ResearchProjectVersion)=>string][]=[["一般向けタイトル",v=>v.step2Response.research_outline.title_public],["メインRQ",v=>v.step2Response.research_outline.main_rq],["対象",v=>v.step2Response.research_outline.target_population],["研究デザイン",v=>v.step2Response.research_outline.research_design],["分析方法",v=>v.step2Response.research_outline.analysis_method],["次のステップ",v=>v.step2Response.research_outline.next_steps.join(" / ")]];return <Card className="version-compare"><h3>主要項目を比較</h3><div className="version-compare-grid"><span></span>{versions.map((v)=><strong key={v.versionId}>{v.versionName}</strong>)}{fields.flatMap(([label,get])=>[<b key={`${label}-label`}>{label}</b>,...versions.map((v)=><p key={`${label}-${v.versionId}`}>{get(v)}</p>)])}</div></Card>; }

function CoverEditor({project,onProject}:{project:ResearchProject;onProject:(p:ResearchProject)=>void}) {
  type BlockKey="title"|"subtitle"|"metadata"|`custom:${string}`;
  const [cover,setCover]=useState(project.cover); const [title,setTitle]=useState(project.displayTitle); const [subtitle,setSubtitle]=useState(project.subtitle); const [saving,setSaving]=useState(false); const [selectedBlock,setSelectedBlock]=useState<BlockKey|null>(null); const [drawing,setDrawing]=useState<"none"|"pen"|"marker"|"eraser">("none"); const [backgroundEditing,setBackgroundEditing]=useState(false); const [drawColor,setDrawColor]=useState("#dff000");
  const coverHistory=useRef<ResearchProjectCover[]>([project.cover]); const historyIndex=useRef(0); const skipHistory=useRef(false); const [,refreshHistory]=useState(0);
  useEffect(()=>{if(skipHistory.current){skipHistory.current=false;return;}const serialized=JSON.stringify(cover);if(JSON.stringify(coverHistory.current[historyIndex.current])===serialized)return;coverHistory.current=[...coverHistory.current.slice(0,historyIndex.current+1),cover].slice(-80);historyIndex.current=coverHistory.current.length-1;refreshHistory((v)=>v+1);},[cover]);
  const travelHistory=(direction:-1|1)=>{const next=historyIndex.current+direction;if(next<0||next>=coverHistory.current.length)return;historyIndex.current=next;skipHistory.current=true;setCover(coverHistory.current[next]);refreshHistory((v)=>v+1);};
  const updateBlock=(key:"title"|"subtitle"|"metadata",patch:Partial<ResearchProjectCover["title"]>)=>setCover((current)=>({...current,[key]:{...current[key],...patch}}));
  const updateCustom=(id:string,patch:{text?:string;block?:Partial<ResearchProjectCover["title"]>})=>setCover((current)=>({...current,textBoxes:(current.textBoxes||[]).map((box)=>box.id===id?{...box,text:patch.text??box.text,block:{...box.block,...patch.block}}:box)}));
  const addTextBox=()=>{const id=`text-${Date.now()}`;setCover((current)=>({...current,textBoxes:[...(current.textBoxes||[]),{id,text:"補足テキスト",block:{...current.subtitle,x:10,y:72,width:80,fontSize:14}}]}));setSelectedBlock(`custom:${id}`);};
  const removeTextBox=(id:string)=>{setCover((current)=>({...current,textBoxes:(current.textBoxes||[]).filter((box)=>box.id!==id)}));setSelectedBlock(null);};
  const moveBlock=(key:BlockKey,x:number,y:number)=>{if(key==="title"||key==="subtitle"||key==="metadata"){updateBlock(key,{x,y});return;}updateCustom(key.slice(7),{block:{x,y}});};
  const changeText=(key:BlockKey,value:string)=>{if(key==="title")setTitle(value);else if(key==="subtitle")setSubtitle(value);else if(key==="metadata")setCover((current)=>({...current,metadataText:value}));else updateCustom(key.slice(7),{text:value});};
  const save=async()=>{setSaving(true);try{const {project:p}=await api.updateProject(project.id,{cover,displayTitle:title,subtitle});onProject(p);}finally{setSaving(false);}};
  const existingMotifs=()=>motifsOf(cover);
  const updateMotif=(id:string,patch:Partial<NonNullable<ResearchProjectCover["motifs"]>[number]>)=>setCover((current)=>({...current,motif:undefined,motifs:motifsOf(current).map((motif)=>motif.id===id?{...motif,...patch}:motif)}));
  const addMotif=(motif:Omit<NonNullable<ResearchProjectCover["motifs"]>[number],"id">)=>setCover((current)=>({...current,motif:undefined,motifs:[...motifsOf(current),{id:`motif-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,...motif}]}));
  const moveMotifLayer=(id:string,direction:-1|1)=>setCover((current)=>{const motifs=motifsOf(current);const index=motifs.findIndex((item)=>item.id===id);const target=index+direction;if(index<0||target<0||target>=motifs.length)return current;const next=[...motifs];[next[index],next[target]]=[next[target],next[index]];return {...current,motif:undefined,motifs:next};});
  const removeMotif=(id:string)=>setCover((current)=>({...current,motif:undefined,motifs:motifsOf(current).filter((item)=>item.id!==id)}));
  const upload=(kind:"background"|"motif",file?:File)=>{if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){alert("PNG・JPEG・WebP画像だけを使用できます");return;}if(file.size>5*1024*1024){alert("画像は5MB以下にしてください");return;}const reader=new FileReader();reader.onload=async()=>{setSaving(true);try{const result=await api.uploadProjectCoverImage(project.id,{dataUrl:String(reader.result),fileName:file.name,kind});if(kind==="background"){setCover((current)=>({...current,backgroundType:"image",autoTextContrast:true,image:{...result.image,scale:1,x:50,y:50,fit:"cover"}}));setDrawing("none");setBackgroundEditing(true);}else addMotif({name:file.name,dataUrl:result.image.dataUrl,storagePath:result.image.storagePath,mimeType:result.image.mimeType,scale:58,x:50,y:55,rotation:0,opacity:1,shadow:14});}catch(e){alert(e instanceof Error?e.message:"画像を保存できませんでした");}finally{setSaving(false);}};reader.readAsDataURL(file);};
  const useSignatureMotif=()=>addMotif({name:"MISHIRU モチーフ",dataUrl:"/assets/motifs/mishiru-sculpture.png",scale:72,x:58,y:60,rotation:0,opacity:1,shadow:20});
  const updateStroke=(stroke:NonNullable<ResearchProjectCover["strokes"]>[number])=>setCover((current)=>({...current,strokes:(current.strokes||[]).some((item)=>item.id===stroke.id)?(current.strokes||[]).map((item)=>item.id===stroke.id?stroke:item):[...(current.strokes||[]),stroke]}));
  const eraseAt=(point:{x:number;y:number})=>setCover((current)=>({...current,strokes:(current.strokes||[]).filter((stroke)=>!stroke.points.some((sample)=>Math.hypot(sample.x-point.x,sample.y-point.y)<6))}));
  const changeBackground=(patch:{x?:number;y?:number;scale?:number})=>setCover((current)=>current.image?({...current,image:{...current.image,...patch}}):current);
  const manualBlock=(key:"title"|"subtitle"|"metadata",patch:Partial<ResearchProjectCover["title"]>)=>{if(patch.color)setCover((current)=>({...current,autoTextContrast:false}));updateBlock(key,patch);};
  const manualCustom=(id:string,patch:Partial<ResearchProjectCover["title"]>)=>{if(patch.color)setCover((current)=>({...current,autoTextContrast:false}));updateCustom(id,{block:patch});};
  return <section className="project-panel cover-editor"><div className="panel-heading"><div><p className="eyebrow">BOOK COVER STUDIO</p><h2>本のデザインを編集する</h2><p>プレビュー上で背景・文字・モチーフを直接動かせます</p></div><div className="cover-editor-actions"><button type="button" title="一つ戻す" aria-label="一つ戻す" disabled={historyIndex.current===0} onClick={()=>travelHistory(-1)}><Undo2/></button><button type="button" title="一つ進める" aria-label="一つ進める" disabled={historyIndex.current>=coverHistory.current.length-1} onClick={()=>travelHistory(1)}><Redo2/></button><Button onClick={save} disabled={saving}>{saving&&<LoaderCircle className="animate-spin"/>}<Save/>保存</Button></div></div><div className="cover-editor-grid"><div className="cover-stage"><ProjectCover project={{...project,displayTitle:title,subtitle,cover}} editable selectedBlock={selectedBlock||undefined} drawing={drawing==="pen"||drawing==="marker"} erasing={drawing==="eraser"} backgroundEditing={backgroundEditing} drawColor={drawColor} drawWidth={drawing==="marker"?16:4} drawOpacity={drawing==="marker"?.32:.9} onSelectBlock={setSelectedBlock} onBlockPositionChange={moveBlock} onTextChange={changeText} onMotifPositionChange={(id,x,y)=>updateMotif(id,{x,y})} onStrokeChange={updateStroke} onEraseAt={eraseAt} onBackgroundChange={changeBackground}/><small>{backgroundEditing?"背景をドラッグ・スクロールして位置と大きさを調整":drawing==="eraser"?"消したい線をなぞります":drawing!=="none"?"表紙の上をなぞって描画できます":"ドラッグで移動・文字はダブルクリックで編集"}</small></div><div className="cover-controls">
    <CoverPanel number="01" title="デザインプリセット"><div className="preset-row">{["electric","lime","silver","charcoal"].map((id)=><button aria-label={`${id}プリセット`} key={id} onClick={()=>setCover(presetCover(id,cover))} style={{background:id==='electric'?'linear-gradient(145deg,#1e40ff,#002b94)':id==='lime'?'linear-gradient(145deg,#f1ff52,#c6d900)':id==='silver'?'linear-gradient(145deg,#fff,#b9c3d1)':'#111317'}}/>)}</div></CoverPanel>
    <CoverPanel number="02" title="背景"><div className="segment-control"><button className={cover.backgroundType==='solid'?'active':''} onClick={()=>setCover({...cover,backgroundType:'solid'})}>単色</button><button className={cover.backgroundType==='gradient'?'active':''} onClick={()=>setCover({...cover,backgroundType:'gradient'})}>グラデーション</button><button className={cover.backgroundType==='image'?'active':''} disabled={!cover.image} onClick={()=>setCover({...cover,backgroundType:'image'})}>画像</button></div><Color label="ベースカラー" value={cover.solidColor} onChange={(v)=>setCover({...cover,solidColor:v})}/>{cover.backgroundType==='gradient'&&<><Color label="開始色" value={cover.gradientStart} onChange={(v)=>setCover({...cover,gradientStart:v})}/><Color label="終了色" value={cover.gradientEnd} onChange={(v)=>setCover({...cover,gradientEnd:v})}/><Range label="角度" min={0} max={360} value={cover.gradientAngle} onChange={(v)=>setCover({...cover,gradientAngle:v})}/></>}<label className="image-upload"><ImagePlus/>背景画像をアップロード<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>upload("background",e.target.files?.[0])}/></label>{cover.image&&<div className="control-stack"><div className="segment-control"><button className={(cover.image.fit||"cover")==="cover"?"active":""} onClick={()=>setCover({...cover,image:{...cover.image!,fit:"cover",scale:1}})}>枠いっぱいに切り取る</button><button className={cover.image.fit==="contain"?"active":""} onClick={()=>setCover({...cover,image:{...cover.image!,fit:"contain"}})}>全体を収める</button></div><button className={`background-direct-edit ${backgroundEditing?"active":""}`} onClick={()=>{setDrawing("none");setBackgroundEditing((value)=>!value);}}><ImagePlus/>{backgroundEditing?"背景の調整を終了":"プレビュー上で位置・大きさを調整"}</button><div className="background-zoom-buttons"><button onClick={()=>changeBackground({scale:Math.max(1,cover.image!.scale-.1)})}>−</button><span>{Math.round(cover.image.scale*100)}%</span><button onClick={()=>changeBackground({scale:Math.min(3,cover.image!.scale+.1)})}>＋</button></div><Color label="色の重なり" value={cover.image.overlayColor} onChange={(v)=>setCover({...cover,image:{...cover.image!,overlayColor:v}})}/><Range label="重なりの濃さ" min={0} max={100} value={cover.image.overlayOpacity*100} onChange={(v)=>setCover({...cover,image:{...cover.image!,overlayOpacity:v/100}})}/><button className="danger-link" onClick={()=>setCover({...cover,backgroundType:'solid',image:undefined})}><Trash2/>背景画像を削除</button></div>}</CoverPanel>
    <CoverPanel number="03" title="モチーフ"><div className="motif-actions"><button className="motif-library" onClick={useSignatureMotif}><img src="/assets/motifs/mishiru-sculpture.png" alt=""/><span><b>MISHIRUモチーフ</b><small>何個でも追加できます</small></span></button><label className="image-upload"><ImagePlus/>手持ちの画像を追加<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>upload("motif",e.target.files?.[0])}/></label></div><p className="motif-order-help">リストの下側ほど表紙の前面に表示されます</p><div className="motif-layer-list">{existingMotifs().map((motif,index)=><details key={motif.id}><summary><img src={motif.dataUrl} alt=""/><span><b>{motif.name||`追加素材 ${index+1}`}</b><small>{index===existingMotifs().length-1?"最前面":`レイヤー ${index+1}`}</small></span><ChevronDown/></summary><div className="control-stack"><Range label="大きさ" min={10} max={180} value={motif.scale} onChange={(v)=>updateMotif(motif.id,{scale:v})}/><Range label="横位置" min={0} max={100} value={motif.x} onChange={(v)=>updateMotif(motif.id,{x:v})}/><Range label="縦位置" min={0} max={100} value={motif.y} onChange={(v)=>updateMotif(motif.id,{y:v})}/><Range label="回転" min={-180} max={180} value={motif.rotation} onChange={(v)=>updateMotif(motif.id,{rotation:v})}/><Range label="透明度" min={10} max={100} value={motif.opacity*100} onChange={(v)=>updateMotif(motif.id,{opacity:v/100})}/><Range label="影" min={0} max={50} value={motif.shadow} onChange={(v)=>updateMotif(motif.id,{shadow:v})}/><div className="layer-order-actions"><button disabled={index===0} onClick={()=>moveMotifLayer(motif.id,-1)}>背面へ</button><button disabled={index===existingMotifs().length-1} onClick={()=>moveMotifLayer(motif.id,1)}>前面へ</button></div><div className="layer-actions"><button onClick={()=>addMotif({...motif,name:`${motif.name||"追加素材"} のコピー`,x:Math.min(90,motif.x+6),y:Math.min(90,motif.y+6)})}><Copy/>複製</button><button className="danger-link" onClick={()=>removeMotif(motif.id)}><Trash2/>削除</button></div></div></details>)}</div></CoverPanel>
    <CoverPanel number="04" title="ペン・マーカー"><div className="drawing-tools"><button className={drawing==="pen"?"active":""} onClick={()=>{setBackgroundEditing(false);setDrawing(drawing==="pen"?"none":"pen");}}><PenTool/>サインペン</button><button className={drawing==="marker"?"active":""} onClick={()=>{setBackgroundEditing(false);setDrawing(drawing==="marker"?"none":"marker");}}><Highlighter/>マーカー</button><button className={drawing==="eraser"?"active":""} onClick={()=>{setBackgroundEditing(false);setDrawing(drawing==="eraser"?"none":"eraser");}}><Eraser/>消しゴム</button></div><Color label="描画色" value={drawColor} onChange={setDrawColor}/>{(cover.strokes||[]).length>0&&<button className="danger-link" onClick={()=>setCover({...cover,strokes:[]})}><Trash2/>描画をすべて消す</button>}</CoverPanel>
    <CoverPanel number="05" title="文字の読みやすさ"><label className="auto-contrast-toggle"><input type="checkbox" checked={cover.autoTextContrast!==false} onChange={(e)=>setCover({...cover,autoTextContrast:e.target.checked})}/><span><b>背景に合わせて文字色を自動調整</b><small>文字色を選び直すと手動設定になります</small></span></label><Color label="重ねる色" value={cover.readabilityOverlay?.color||"#000000"} onChange={(v)=>setCover({...cover,readabilityOverlay:{color:v,opacity:cover.readabilityOverlay?.opacity||0}})}/><Range label="重ねる濃さ" min={0} max={80} value={(cover.readabilityOverlay?.opacity||0)*100} onChange={(v)=>setCover({...cover,readabilityOverlay:{color:cover.readabilityOverlay?.color||"#000000",opacity:v/100}})}/></CoverPanel>
    <CoverPanel number="06" title="文字レイヤー"><div className="cover-text-editor"><p className="cover-control-help">行を押して開閉できます。プレビュー上ではダブルクリックで直接入力できます</p>{([['title','タイトル',title,setTitle],['subtitle','サブタイトル',subtitle,setSubtitle]] as const).map(([key,label,value,setValue])=><TextLayerEditor key={key} label={label} value={value} block={cover[key]} selected={selectedBlock===key} onSelect={()=>setSelectedBlock(selectedBlock===key?null:key)} onText={setValue} onBlock={(patch)=>manualBlock(key,patch)}/>)}<TextLayerEditor label="署名・シリーズ名" value={cover.metadataText||"RESEARCH PROJECT\nMISHIRU"} block={cover.metadata} selected={selectedBlock==='metadata'} onSelect={()=>setSelectedBlock(selectedBlock==='metadata'?null:'metadata')} onText={(value)=>setCover({...cover,metadataText:value})} onBlock={(patch)=>manualBlock('metadata',patch)}/>{(cover.textBoxes||[]).map((box)=><TextLayerEditor key={box.id} label="追加テキスト" value={box.text} block={box.block} selected={selectedBlock===`custom:${box.id}`} onSelect={()=>setSelectedBlock(selectedBlock===`custom:${box.id}`?null:`custom:${box.id}`)} onText={(text)=>updateCustom(box.id,{text})} onBlock={(patch)=>manualCustom(box.id,patch)} onRemove={()=>removeTextBox(box.id)}/>)}<button type="button" className="add-text-layer" onClick={addTextBox}><Plus/>テキストボックスを追加</button></div></CoverPanel>
  </div></div></section>;
}
function CoverPanel({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <details className="cover-panel"><summary><span>{number}</span><b>{title}</b><ChevronDown/></summary><div className="cover-panel__body">{children}</div></details>}
function motifsOf(cover:ResearchProjectCover):NonNullable<ResearchProjectCover["motifs"]>{return cover.motifs?.length?cover.motifs:cover.motif?[{id:"legacy-motif",...cover.motif}]:[];}
function TextLayerEditor({label,value,block,selected,onSelect,onText,onBlock,onRemove}:{label:string;value:string;block:ResearchProjectCover["title"];selected:boolean;onSelect:()=>void;onText?:(value:string)=>void;onBlock:(patch:Partial<ResearchProjectCover["title"]>)=>void;onRemove?:()=>void}) { return <div className={`cover-text-layer ${selected?"is-selected":""}`}><button type="button" className="cover-text-layer__header" onClick={onSelect} aria-expanded={selected}><span>{label}</span><small>{Math.round(block.x)}%, {Math.round(block.y)}%</small><ChevronDown/></button>{selected&&<div className="cover-text-layer__body"><label>テキスト<textarea rows={2} value={value} onChange={(e)=>onText?.(e.target.value)}/></label><label>フォント<select value={block.fontFamily} onChange={(e)=>onBlock({fontFamily:e.target.value})}>{FONT_OPTIONS.map((font)=><option key={font}>{font}</option>)}</select></label><Color label="文字色" value={block.color} onChange={(v)=>onBlock({color:v})}/><Range label="サイズ" min={8} max={64} value={block.fontSize} onChange={(v)=>onBlock({fontSize:v})}/><Range label="太さ" min={300} max={900} step={100} value={block.fontWeight} onChange={(v)=>onBlock({fontWeight:v})}/><Range label="行間 ×100" min={90} max={220} value={block.lineHeight*100} onChange={(v)=>onBlock({lineHeight:v/100})}/><Range label="字間" min={0} max={12} value={block.letterSpacing} onChange={(v)=>onBlock({letterSpacing:v})}/><div className="segment-control" aria-label="文字揃え">{(['left','center','right'] as const).map((align)=><button type="button" className={block.align===align?'active':''} onClick={()=>onBlock({align})} key={align}>{align==='left'?'左揃え':align==='center'?'中央':'右揃え'}</button>)}</div><Range label="横位置" min={0} max={95} value={block.x} onChange={(v)=>onBlock({x:v})}/><Range label="縦位置" min={0} max={95} value={block.y} onChange={(v)=>onBlock({y:v})}/><Range label="テキスト幅" min={15} max={100} value={block.width} onChange={(v)=>onBlock({width:v})}/>{onRemove&&<button type="button" className="danger-link" onClick={onRemove}><Trash2/>このテキストボックスを削除</button>}</div>}</div>; }
const FONT_OPTIONS=["Hiragino Mincho ProN","Yu Mincho","Noto Serif JP","Shippori Mincho","Arai","Noto Sans JP","Yu Gothic","せのびゴシック","Hiragino Sans","Georgia","Arial"];
function presetCover(id:string,current:ResearchProjectCover):ResearchProjectCover { const color=id==='lime'||id==='silver'?'#06111f':'#fff';const [a,b]=id==='electric'?['#1e40ff','#002b94']:id==='lime'?['#f1ff52','#c6d900']:id==='silver'?['#fff','#bac6d8']:['#111317','#111317'];return {...current,presetId:id,backgroundType:id==='charcoal'?'solid':'gradient',solidColor:a,gradientStart:a,gradientEnd:b,autoTextContrast:true,readabilityOverlay:{color:'#000000',opacity:(id==='electric'||id==='charcoal')?0.16:0},title:{...current.title,color,fontFamily:current.title.fontFamily||'Hiragino Mincho ProN'},subtitle:{...current.subtitle,color,fontFamily:current.subtitle.fontFamily||'Hiragino Mincho ProN'},metadata:{...current.metadata,color:id==='electric'?'#dff000':color}};}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) {const [hue,setHue]=useState(225);const pick=(event:PointerEvent<HTMLDivElement>)=>{const rect=event.currentTarget.getBoundingClientRect();const s=Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100));const l=Math.max(4,Math.min(96,100-(event.clientY-rect.top)/rect.height*100));onChange(hslToHex(hue,s,l));};return <details className="color-studio"><summary><span>{label}</span><i style={{background:value}}/><code>{value.toUpperCase()}</code><ChevronDown/></summary><div className="color-studio__panel"><div className="color-plane" style={{backgroundColor:`hsl(${hue} 100% 50%)`}} onPointerDown={pick} onPointerMove={(e)=>e.buttons===1&&pick(e)}/><input className="hue-range" aria-label={`${label}の色相`} type="range" min={0} max={360} value={hue} onChange={(e)=>setHue(Number(e.target.value))}/><div className="color-value"><input type="color" value={value} onChange={(e)=>onChange(e.target.value)}/><input aria-label={`${label}のカラーコード`} value={value} onChange={(e)=>/^#[0-9a-f]{6}$/i.test(e.target.value)&&onChange(e.target.value)}/></div></div></details>;}
function Range({label,min,max,value,onChange,step=1}:{label:string;min:number;max:number;value:number;onChange:(v:number)=>void;step?:number}) {return <label className="range-control"><span>{label}<b>{Math.round(value)}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={(e)=>onChange(Number(e.target.value))}/></label>;}
function hslToHex(h:number,s:number,l:number){s/=100;l/=100;const a=s*Math.min(l,1-l);const f=(n:number)=>{const k=(n+h/30)%12;return l-a*Math.max(-1,Math.min(k-3,9-k,1));};return `#${[f(0),f(8),f(4)].map((v)=>Math.round(v*255).toString(16).padStart(2,"0")).join("")}`;}
function Info({label,value}:{label:string;value:string}){return <div className="info-row"><dt>{label}</dt><dd>{value}</dd></div>;}
function materialKey(item:NormalizedResearchMaterial){return `${item.sourceType}:${item.sourceId}`;}
function toggle(values:string[],value:string){return values.includes(value)?values.filter((v)=>v!==value):[...values,value];}
