import { useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, Ban, BookOpen, BrainCircuit, Check, Clock3, Database, LoaderCircle, Radar, RotateCcw, Search } from "lucide-react";
import type { InterestAnalysis, NormalizedResearchMaterial } from "../../shared/research-project";
import { api } from "../lib/api";
import { loadQuestionMaterials, materialTypeLabel } from "../lib/questionMaterials";
import { Button, Card, Chip, ErrorState, Skeleton, TrustNote } from "../components/ui";

const materialKey=(item:NormalizedResearchMaterial)=>`${item.sourceType}:${item.sourceId}`;

export default function Reflect(){
  const [analysis,setAnalysis]=useState<InterestAnalysis|null>(null); const [materials,setMaterials]=useState<NormalizedResearchMaterial[]>([]);
  const [excluded,setExcluded]=useState<string[]>([]); const [usage,setUsage]=useState({dailyAnalysisCount:0,planLimit:null as number|null,canAnalyze:true});
  const [aiEnabled,setAiEnabled]=useState(false); const [state,setState]=useState<"loading"|"ready"|"error"|"updating">("loading"); const [error,setError]=useState("");
  const load=async()=>{setState("loading");try{const [meta,items]=await Promise.all([api.getInterestAnalysis(),loadQuestionMaterials()]);setAnalysis(meta.analysis);setExcluded(meta.analysis?.excludedSourceIds||[]);setUsage(meta.usage);setAiEnabled(meta.aiEnabled);setMaterials(items);setState("ready");}catch(e){setError(e instanceof Error?e.message:"関心の現在地を読み込めませんでした");setState("error");}};
  useEffect(()=>{load();},[]);
  const update=async()=>{if(state==="updating")return;setState("updating");setError("");try{const result=await api.updateInterestAnalysis(materials,excluded);setAnalysis(result.analysis);setUsage(result.usage);setAiEnabled(result.aiEnabled);setState("ready");}catch(e){setError(e instanceof Error?e.message:"更新できませんでした");setState("ready");}};
  const usedIds=new Set(analysis?.sourceSnapshot.map(materialKey)||[]); const added=materials.filter((item)=>!usedIds.has(materialKey(item))).length;
  const direction=analysis?.result.directions.interestDirections[0]||"";
  const questionLink=analysis?`/questions?interestAnalysisId=${encodeURIComponent(analysis.id)}&materialIds=${encodeURIComponent(analysis.result.evidence.sourceIds.join(','))}&direction=${encodeURIComponent(direction)}`:"/questions";
  if(state==="loading")return <div className="max-w-5xl mx-auto px-4 py-8"><Skeleton className="h-40"/><Skeleton className="h-80 mt-4"/></div>;
  if(state==="error")return <div className="max-w-4xl mx-auto px-4 py-8"><ErrorState message={error} onRetry={load}/></div>;
  return <div className="reflect-page max-w-6xl mx-auto px-4 md:px-6 py-6 md:py-10"><Helmet><title>みつめる ｜ MISHIRU</title></Helmet>
    <header className="reflect-heading"><div><p className="eyebrow">関心を整理</p><h1>いま気になっていること</h1><p>保存したものと反応をもとに、関心の共通点と次に調べることを整理します。</p></div><Button onClick={update} disabled={state==="updating"||!usage.canAnalyze||materials.length===0}>{state==="updating"?<><LoaderCircle className="animate-spin"/>関心を整理中…</>:<><RotateCcw/>関心を整理する</>}</Button></header>
    <div className="reflect-status"><div className="stat-tile"><span><Clock3/>整理した日時</span><strong>{analysis?new Date(analysis.lastAnalyzedAt).toLocaleString("ja-JP",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):"まだありません"}</strong></div><div className="stat-tile"><span><Database/>使った材料</span><strong>{analysis?.sourceSnapshot.length||0}<small>件</small></strong></div><div className="stat-tile"><span><Radar/>新しい材料</span><strong>{added}<small>件</small></strong></div><div className="stat-tile"><span><BrainCircuit/>今日の利用</span><strong>{usage.dailyAnalysisCount}<small>{usage.planLimit===null?"回":` / ${usage.planLimit}回`}</small></strong></div></div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {!analysis?<Card className="reflect-empty"><Radar/><h2>保存したものから関心を整理する</h2><p>問いや研究室への反応をまとめると、共通するテーマと次の探し方が見えてきます。</p><span>{materials.length}件の材料を使えます</span>{materials.length===0&&<Link to="/discover">問いのカードを見る<ArrowRight/></Link>}</Card>:<div className="reflect-blocks">
      <ReflectBlock number="01" title="いま見えている関心"><Group label="強く反応しているテーマ" values={analysis.result.current.strongThemes}/><Group label="よく現れる対象" values={analysis.result.current.objects}/><Group label="現象・明示された問い" values={analysis.result.current.phenomena}/><Group label="場面・文脈" values={analysis.result.current.contexts}/><Group label="問い方の傾向" values={analysis.result.current.questionStyles}/><SignalGrid positive={analysis.result.current.positiveInterests} negative={analysis.result.current.negativeReactions} undecided={analysis.result.current.undecided}/><Group label="関心の変化" values={analysis.result.current.changes}/></ReflectBlock>
      <ReflectBlock number="02" title="近い研究を見つける"><ConnectionPath direction={direction} field={analysis.result.connections.fields[0]?.name} lab={analysis.result.connections.labs[0]?.name}/><ResourceLinks label="近い研究領域" values={analysis.result.connections.fields} base="/search?resource=fields&q="/><ResourceLinks label="近い研究室" values={analysis.result.connections.labs} base="/labs/" direct/><ResourceLinks label="近い学会" values={analysis.result.connections.societies} base="/search?resource=societies&q="/><ResourceLinks label="近いジャーナル" values={analysis.result.connections.journals} base="/search?resource=journals&q="/><Group label="検索に使える言葉" values={analysis.result.connections.searchTerms}/><Group label="次に見るもの" values={analysis.result.connections.nextTargets}/></ReflectBlock>
      <ReflectBlock number="03" title="問いにできそうな方向"><Group label="関心が向かっている方向" values={analysis.result.directions.interestDirections}/><Group label="対象を絞れそうな方向" values={analysis.result.directions.narrowingDirections}/><Group label="分けて考えた方がよい論点" values={analysis.result.directions.separateIssues}/><Group label="まだ広すぎる部分" values={analysis.result.directions.broadAreas}/><Group label="方法を考える前に確認したいこと" values={analysis.result.directions.confirmations}/><Group label="次にためるとよい情報" values={analysis.result.directions.nextMaterials}/><Link className="reflect-question-cta" to={questionLink}><span><strong>この関心から問いにしてみる</strong><small>根拠素材と選んだ方向を引き継ぎます</small></span><ArrowRight/></Link></ReflectBlock>
      <ReflectBlock number="04" title="整理に使った材料"><p className="evidence-summary">{analysis.result.evidence.summary}</p><div className="reaction-counts">{Object.entries(analysis.result.evidence.reactionCounts).map(([key,value])=><Chip key={key}>{key} {value}</Chip>)}</div><div className="evidence-list">{analysis.sourceSnapshot.map((item)=>{const key=materialKey(item);const removed=excluded.includes(key);return <label key={`${key}:${item.userReaction}`} className={removed?"excluded":""}><input type="checkbox" checked={!removed} onChange={()=>setExcluded((items)=>items.includes(key)?items.filter((id)=>id!==key):[...items,key])}/><span><Chip tone="blue">{materialTypeLabel[item.sourceType]||item.sourceType}</Chip><strong>{item.title}</strong><small>{[item.userReaction,item.userReasonMemo].filter(Boolean).join(" ・ ")}</small></span>{removed?<Ban/>:<Check/>}</label>;})}</div><TrustNote>チェックを外した材料は、次に整理するときに使いません。過去の結果は残ります。</TrustNote></ReflectBlock>
    </div>}
  </div>;
}

function ReflectBlock({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="reflect-block"><div className="reflect-block-title"><span>{number}</span><h2>{title}</h2></div><div className="reflect-block-body">{children}</div></section>;}
function Group({label,values}:{label:string;values:string[]}){return <div className="reflect-group"><h3>{label}</h3>{values.length?<div>{values.map((value,index)=><span key={`${value}:${index}`}>{value}</span>)}</div>:<p>まだ見つかっていません</p>}</div>;}
function SignalGrid({positive,negative,undecided}:{positive:string[];negative:string[];undecided:string[]}){return <div className="signal-grid"><Group label="肯定的関心" values={positive}/><Group label="否定的反応" values={negative}/><Group label="まだ判断できていないもの" values={undecided}/></div>;}
function ResourceLinks({label,values,base,direct=false}:{label:string;values:{id:string;name:string}[];base:string;direct?:boolean}){return <div className="reflect-group"><h3>{label}</h3><div>{values.map((item)=><Link key={item.id} to={direct?`${base}${item.id}`:`${base}${encodeURIComponent(item.name)}`}><Search/>{item.name}</Link>)}</div></div>;}
function ConnectionPath({direction,field,lab}:{direction:string;field?:string;lab?:string}){const nodes=[{label:"気になっていること",value:direction||"整理中"},{label:"近い研究領域",value:field||"候補を探しています"},{label:"近い研究室",value:lab||"候補を探しています"}];return <div className="reflect-connection-map" aria-label="関心から近い研究を探す流れ">{nodes.map((node,index)=><div key={node.label} className="reflect-connection-node"><small>{String(index+1).padStart(2,"0")} / {node.label}</small><strong>{node.value}</strong></div>)}</div>;}
