import { useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, Ban, BookOpen, BrainCircuit, Check, Clock3, Database, LoaderCircle, Radar, RotateCcw, Search } from "lucide-react";
import type { InterestAnalysis, NormalizedResearchMaterial } from "../../shared/research-project";
import { api } from "../lib/api";
import { loadQuestionMaterials, materialTypeLabel } from "../lib/questionMaterials";
import { Button, Card, Chip, ErrorState, Skeleton } from "../components/ui";

const materialKey=(item:NormalizedResearchMaterial)=>`${item.sourceType}:${item.sourceId}`;

export default function Reflect(){
  const [analysis,setAnalysis]=useState<InterestAnalysis|null>(null); const [materials,setMaterials]=useState<NormalizedResearchMaterial[]>([]);
  const [excluded,setExcluded]=useState<string[]>([]); const [usage,setUsage]=useState({dailyAnalysisCount:0,planLimit:null as number|null,canAnalyze:true});
  const [aiEnabled,setAiEnabled]=useState(false); const [state,setState]=useState<"loading"|"ready"|"error"|"updating">("loading"); const [error,setError]=useState("");
  const load=async()=>{setState("loading");try{const [meta,items]=await Promise.all([api.getInterestAnalysis(),loadQuestionMaterials()]);setAnalysis(meta.analysis);setExcluded(meta.analysis?.excludedSourceIds||[]);setUsage(meta.usage);setAiEnabled(meta.aiEnabled);setMaterials(items);setState("ready");}catch(e){setError(e instanceof Error?e.message:"関心の現在地を読み込めませんでした");setState("error");}};
  useEffect(()=>{load();},[]);
  const update=async()=>{if(state==="updating")return;setState("updating");setError("");try{const result=await api.updateInterestAnalysis(materials,excluded);setAnalysis(result.analysis);setUsage(result.usage);setAiEnabled(result.aiEnabled);setState("ready");}catch(e){setError(e instanceof Error?e.message:"更新できませんでした");setState("ready");}};
  const usedIds=new Set(analysis?.sourceSnapshot.map(materialKey)||[]); const added=materials.filter((item)=>!usedIds.has(materialKey(item))).length;
  const direction=analysis?.result.directions.interestDirections[0]||"";
  const questionLink=analysis?`/questions?interestAnalysisId=${encodeURIComponent(analysis.id)}&materialIds=${encodeURIComponent(analysis.result.evidence.sourceIds.join(','))}&direction=${encodeURIComponent(direction)}`:"/questions";
  if(state==="loading")return <div className="max-w-5xl mx-auto px-4 py-8"><Skeleton className="h-40"/><Skeleton className="h-80 mt-4"/></div>;
  if(state==="error")return <div className="max-w-4xl mx-auto px-4 py-8"><ErrorState message={error} onRetry={load}/></div>;
  return <div className="reflect-page max-w-6xl mx-auto px-4 md:px-6 py-6 md:py-10"><Helmet><title>みつめる ｜ MISHIRU</title></Helmet>
    <header className="reflect-heading"><div><p className="eyebrow">INTEREST POSITION</p><h1>関心の現在地</h1><p>ためた素材と反応を、必要なときだけ更新して見つめます。完成した問いはここでは作りません。</p></div><Button onClick={update} disabled={state==="updating"||!usage.canAnalyze||materials.length===0}>{state==="updating"?<LoaderCircle className="animate-spin"/>:<RotateCcw/>}関心の現在地を更新</Button></header>
    <Card className="reflect-status"><div><Clock3/><span>最終更新<strong>{analysis?new Date(analysis.lastAnalyzedAt).toLocaleString("ja-JP",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):"まだ更新していません"}</strong></span></div><div><Database/><span>分析対象<strong>{analysis?.sourceSnapshot.length||0}件</strong></span></div><div><Radar/><span>前回後の追加<strong>{added}件</strong></span></div><div><BrainCircuit/><span>本日の更新<strong>{usage.dailyAnalysisCount}{usage.planLimit===null?"回（開発環境・無制限）":` / ${usage.planLimit}回`}</strong></span></div></Card>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {!analysis?<Card className="reflect-empty"><Radar/><h2>最初の現在地をつくる</h2><p>であう・ためる・マーキングで材料を追加した後、「関心の現在地を更新」を押してください。自動分析は行いません。</p><span>{materials.length}件の素材を確認できます</span></Card>:<div className="reflect-blocks">
      <ReflectBlock number="01" title="いま見えている関心"><Group label="強く反応しているテーマ" values={analysis.result.current.strongThemes}/><Group label="よく現れる対象" values={analysis.result.current.objects}/><Group label="現象・明示された問い" values={analysis.result.current.phenomena}/><Group label="場面・文脈" values={analysis.result.current.contexts}/><Group label="問い方の傾向" values={analysis.result.current.questionStyles}/><SignalGrid positive={analysis.result.current.positiveInterests} negative={analysis.result.current.negativeReactions} undecided={analysis.result.current.undecided}/><Group label="関心の変化" values={analysis.result.current.changes}/></ReflectBlock>
      <ReflectBlock number="02" title="研究世界との接続"><ConnectionPath direction={direction} field={analysis.result.connections.fields[0]?.name} lab={analysis.result.connections.labs[0]?.name}/><ResourceLinks label="近い研究領域" values={analysis.result.connections.fields} base="/search?resource=fields&q="/><ResourceLinks label="近い研究室" values={analysis.result.connections.labs} base="/labs/" direct/><ResourceLinks label="近い学会" values={analysis.result.connections.societies} base="/search?resource=societies&q="/><ResourceLinks label="近いジャーナル" values={analysis.result.connections.journals} base="/search?resource=journals&q="/><Group label="検索に使える言葉" values={analysis.result.connections.searchTerms}/><Group label="次に見てみるとよい対象" values={analysis.result.connections.nextTargets}/></ReflectBlock>
      <ReflectBlock number="03" title="問いにできそうな方向"><Group label="関心が向かっている方向" values={analysis.result.directions.interestDirections}/><Group label="対象を絞れそうな方向" values={analysis.result.directions.narrowingDirections}/><Group label="分けて考えた方がよい論点" values={analysis.result.directions.separateIssues}/><Group label="まだ広すぎる部分" values={analysis.result.directions.broadAreas}/><Group label="方法を考える前に確認したいこと" values={analysis.result.directions.confirmations}/><Group label="次にためるとよい情報" values={analysis.result.directions.nextMaterials}/><Link className="reflect-question-cta" to={questionLink}><span><strong>この関心から問いにしてみる</strong><small>根拠素材と選んだ方向を引き継ぎます</small></span><ArrowRight/></Link></ReflectBlock>
      <ReflectBlock number="04" title="この分析の根拠"><p className="evidence-summary">{analysis.result.evidence.summary}</p><div className="reaction-counts">{Object.entries(analysis.result.evidence.reactionCounts).map(([key,value])=><Chip key={key}>{key} {value}</Chip>)}</div><div className="evidence-list">{analysis.sourceSnapshot.map((item)=>{const key=materialKey(item);const removed=excluded.includes(key);return <label key={`${key}:${item.userReaction}`} className={removed?"excluded":""}><input type="checkbox" checked={!removed} onChange={()=>setExcluded((items)=>items.includes(key)?items.filter((id)=>id!==key):[...items,key])}/><span><Chip tone="blue">{materialTypeLabel[item.sourceType]||item.sourceType}</Chip><strong>{item.title}</strong><small>{[item.userReaction,item.userReasonMemo].filter(Boolean).join(" ・ ")}</small></span>{removed?<Ban/>:<Check/>}</label>;})}</div><p className="evidence-note">除外設定は次回の「関心の現在地を更新」で反映されます。分析時点の素材スナップショットは履歴として保持します。</p></ReflectBlock>
    </div>}
  </div>;
}

function ReflectBlock({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="reflect-block"><div className="reflect-block-title"><span>{number}</span><h2>{title}</h2></div><div className="reflect-block-body">{children}</div></section>;}
function Group({label,values}:{label:string;values:string[]}){return <div className="reflect-group"><h3>{label}</h3>{values.length?<div>{values.map((value,index)=><span key={`${value}:${index}`}>{value}</span>)}</div>:<p>まだ材料がありません</p>}</div>;}
function SignalGrid({positive,negative,undecided}:{positive:string[];negative:string[];undecided:string[]}){return <div className="signal-grid"><Group label="肯定的関心" values={positive}/><Group label="否定的反応" values={negative}/><Group label="まだ判断できていないもの" values={undecided}/></div>;}
function ResourceLinks({label,values,base,direct=false}:{label:string;values:{id:string;name:string}[];base:string;direct?:boolean}){return <div className="reflect-group"><h3>{label}</h3><div>{values.map((item)=><Link key={item.id} to={direct?`${base}${item.id}`:`${base}${encodeURIComponent(item.name)}`}><Search/>{item.name}</Link>)}</div></div>;}
function ConnectionPath({direction,field,lab}:{direction:string;field?:string;lab?:string}){const nodes=[{label:"いまの関心",value:direction||"まだ整理中"},{label:"研究の言葉",value:field||"接続候補を探索中"},{label:"相談の入口",value:lab||"近い研究室を探索中"}];return <div className="reflect-connection-map" aria-label="関心から研究世界への接続">{nodes.map((node,index)=><div key={node.label} className="reflect-connection-node"><small>{String(index+1).padStart(2,"0")} / {node.label}</small><strong>{node.value}</strong></div>)}</div>;}
